auth:
  username: ref+vault://secret/rabbitmq#/username
  password: ref+vault://secret/rabbitmq#/password

service:
  type: LoadBalancer

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: rabbitmq.local
      paths:
        - path: /
          pathType: Prefix
