---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: k8s-hw
  labels:
    app: k8s-test-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-test-app
  template:
    metadata:
      name: k8s-test-app
      labels:
        app: k8s-test-app
        version: v1
    spec:
      containers:
        - name: k8s-test-app
          image: k8s-app:1.0.0
          env:
            - name: CONFIG_MAP_ENV_VAR
              value: testing config map
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
---