apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-test-backend-pvc
  namespace: k8s-hw
  labels:
    app: k8s-test-backend-app
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
