apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  host: {{ .Chart.Name }}-headless-svc.{{ .Release.Namespace }}.svc.cluster.local
  port: {{ .Values.service.port.inner | quote }}
