apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels: {{ include "postgres.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
