apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  VAULT_ADDR: "http://vault.{{ .Release.Namespace }}.svc.cluster.local:8200"
  RMQ_HOST: "rabbitmq.{{ .Release.Namespace }}.svc.cluster.local"
  REDIS_HOST: "redis.{{ .Release.Namespace }}.svc.cluster.local:6379"
