apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.backend.configMapName }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  APP_PORT: {{ .Values.global.backend.port | quote }}
  APP_DATA_DIR: {{ .Values.persistence.mountPath | quote }}
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
