{{- if .Values.cron.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "backend.fullname" . }}-cron
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cron.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "backend.labels" . | nindent 12 }}
            app.kubernetes.io/component: cron
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: {{ .Values.global.imagePullSecret }}
          containers:
            - name: cron
              image: {{ include "backend.image" (list . "cron") | quote }}
              env:
                {{- include "backend.postgresEnv" . | nindent 16 }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
{{- end }}
