apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.backend.serviceName }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.global.backend.servicePort }}
      targetPort: http
