apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: celery-api
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.api.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: celery-api
                port:
                  number: 80
