apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    app: celery-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: worker
          image: {{ .Values.werf.image.worker }}
          envFrom:
            - configMapRef:
                name: celery-config
            - secretRef:
                name: vault-approle
            - secretRef:
                name: celery-broker
