apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels: {{ include "postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{ include "postgres.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgresql
      port: {{ .Values.global.postgres.port }}
      targetPort: postgresql
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  labels: {{ include "postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector: {{ include "postgres.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgresql
      port: {{ .Values.global.postgres.port }}
      targetPort: postgresql
      protocol: TCP
